<a href="https://colab.research.google.com/github/yogeshkumarrudra/Data_structure/blob/main/Pandas04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Merge is very important function is pandas**

pd.merge(df1,df2, on = 'id',how = 'inner')
df1 = dataframe1
df2 = dataframe2
on = merge on which colume
how = which type of join used

In [20]:
from os import rename
df1 = pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Yogesh','Rewas','Parth','sofiya'],
    'age':[23,54,21,20]
})

df2 = pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Samar','Anshu','Mayank','Harshita'],
    'age':[21,40,34,19]
})
#inner join
df3 = pd.merge(df1,df2, on = 'id',how = 'inner')
display(df3)

df3.rename(columns = {'name_x':'Table_one_name1','age_x':'Table_one_age1','name_y':'Table_one_name2','name_y':'Table_one_name2'},inplace = True)
display(df3)

df4 = pd.merge(df1,df2, on = 'id',how = 'left')
display(df4)

df5 = pd.merge(df1,df2, on = 'id',how = 'right')
display(df5)

df6 = pd.merge(df1,df2, on = 'id',how = 'outer')
display(df6)

#cross wale me id nhi dayte hai q ki har ek colume dusre her ek column se intrect kar raha hai
df7 = pd.merge(df1,df2,how = 'cross')
display(df7)

   id  name_x  age_x name_y  age_y
0   3   Parth     21  Samar     21
1   4  sofiya     20  Anshu     40

   id Table_one_name1  Table_one_age1 Table_one_name2  age_y
0   3           Parth              21           Samar     21
1   4          sofiya              20           Anshu     40

   id  name_x  age_x name_y  age_y
0   1  Yogesh     23    NaN    NaN
1   2   Rewas     54    NaN    NaN
2   3   Parth     21  Samar   21.0
3   4  sofiya     20  Anshu   40.0

   id  name_x  age_x    name_y  age_y
0   3   Parth   21.0     Samar     21
1   4  sofiya   20.0     Anshu     40
2   5     NaN    NaN    Mayank     34
3   6     NaN    NaN  Harshita     19

   id  name_x  age_x    name_y  age_y
0   1  Yogesh   23.0       NaN    NaN
1   2   Rewas   54.0       NaN    NaN
2   3   Parth   21.0     Samar   21.0
3   4  sofiya   20.0     Anshu   40.0
4   5     NaN    NaN    Mayank   34.0
5   6     NaN    NaN  Harshita   19.0

    id_x  name_x  age_x  id_y    name_y  age_y
0      1  Yogesh     23     3     Samar     21
1      1  Yogesh     23     4     Anshu     40
2      1  Yogesh     23     5    Mayank     34
3      1  Yogesh     23     6  Harshita     19
4      2   Rewas     54     3     Samar     21
5      2   Rewas     54     4     Anshu     40
6      2   Rewas     54     5    Mayank     34
7      2   Rewas     54     6  Harshita     19
8      3   Parth     21     3     Samar     21
9      3   Parth     21     4     Anshu     40
10     3   Parth     21     5    Mayank     34
11     3   Parth     21     6  Harshita     19
12     4  sofiya     20     3     Samar     21
13     4  sofiya     20     4     Anshu     40
14     4  sofiya     20     5    Mayank     34
15     4  sofiya     20     6  Harshita     19

**Concatination**

In [22]:
df3 = pd.concat([df1,df2])
display(df3)

   id      name  age
0   1    Yogesh   23
1   2     Rewas   54
2   3     Parth   21
3   4    sofiya   20
0   3     Samar   21
1   4     Anshu   40
2   5    Mayank   34
3   6  Harshita   19

**DropDuplicates**

In [ ]:
df2 = pd.DataFrame({
    'id':[3,4,5,6]
})

to_datetime()